# Generated by Django 6.0.2 on 2026-06-14 18:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount_original', models.DecimalField(decimal_places=2, help_text='Amount in the original currency', max_digits=12)),
                ('currency', models.CharField(choices=[('INR', 'INR — Indian Rupee'), ('USD', 'USD — US Dollar')], default='INR', max_length=3)),
                ('amount_inr', models.DecimalField(decimal_places=2, help_text='Amount converted to INR (used for all balance calculations)', max_digits=12)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact Amounts'), ('percentage', 'Percentage'), ('shares', 'Shares / Ratio')], default='equal', max_length=10)),
                ('is_settlement', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.expensegroup')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('clean_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('report_summary', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='core.expensegroup')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_sessions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='1-indexed row number from the CSV')),
                ('raw_row', models.JSONField()),
                ('anomaly_type', models.CharField(choices=[('duplicate', 'Duplicate Row'), ('settlement_as_expense', 'Settlement Recorded as Expense'), ('negative_amount', 'Negative Amount (Possible Refund)'), ('zero_amount', 'Zero Amount'), ('currency_mismatch', 'Currency Mismatch / Missing Currency'), ('post_moveout', 'Expense After Member Move-out'), ('missing_field', 'Missing Required Field'), ('name_inconsistency', 'Inconsistent Name Spelling'), ('percentage_sum', 'Percentage Split Does Not Sum to 100%'), ('exact_sum', 'Exact Split Does Not Sum to Total'), ('unknown_member', 'Unknown Member'), ('future_date', 'Future-Dated Expense'), ('ambiguous_date', 'Ambiguous Date Format'), ('format_error', 'Format Inconsistency'), ('split_conflict', 'Conflicting Split Type and Data'), ('amount_precision', 'Unusual Amount Precision')], max_length=30)),
                ('description', models.TextField(help_text='Human-readable explanation of the issue')),
                ('suggestion', models.TextField(blank=True, default='', help_text='What the system recommends doing with this row')),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved — Import As-Is'), ('modified', 'Approved — Modified Before Import'), ('rejected', 'Rejected — Skip Row'), ('auto_fixed', 'Auto-Fixed')], default='pending', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='', help_text="User's reason for their decision")),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.importsession')),
            ],
            options={
                'db_table': 'import_anomalies',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.expensegroup')),
                ('paid_by', models.ForeignKey(help_text='The person who paid (settling their debt)', on_delete=django.db.models.deletion.CASCADE, related_name='settlements_paid', to=settings.AUTH_USER_MODEL)),
                ('paid_to', models.ForeignKey(help_text='The person who received the payment', on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlements',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, help_text='Original input: percentage (30.0), shares (2), or exact amount', max_digits=10, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='core.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense_splits',
                'unique_together': {('expense', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.expensegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_members',
                'ordering': ['date_joined'],
                'unique_together': {('group', 'user', 'date_joined')},
            },
        ),
    ]
